// ─────────────────────────────────────────────
// skill_profile.dart
//
// This file defines what a "user profile" looks
// like as data in our app.
//
// Think of it like designing a paper form:
// before you can fill in profiles, you need to
// decide exactly which fields the form has.
// ─────────────────────────────────────────────

// ── 1. ENUMS ────────────────────────────────
// An enum is a fixed list of allowed values.
// Instead of storing the string "Beginner" and
// hoping you never typo it as "beginner",
// you store SkillLevel.beginner — and Dart
// catches mistakes at compile time.

/// The proficiency level for a skill.
enum SkillLevel {
  beginner,
  intermediate,
  advanced;

  // .label turns the enum into a display string.
  // e.g.  SkillLevel.beginner.label  →  "Beginner"
  String get label {
    switch (this) {
      case SkillLevel.beginner:
        return 'Beginner';
      case SkillLevel.intermediate:
        return 'Intermediate';
      case SkillLevel.advanced:
        return 'Advanced';
    }
  }

  // .fromString recreates the enum from a stored
  // string (needed when we load data back from storage).
  static SkillLevel fromString(String value) {
    switch (value) {
      case 'intermediate':
        return SkillLevel.intermediate;
      case 'advanced':
        return SkillLevel.advanced;
      default:
        // If the value is unrecognised, default to beginner
        // so the app never crashes on bad data.
        return SkillLevel.beginner;
    }
  }
}

/// Where the user is happy to meet / learn.
enum LearningMode {
  online,
  offline,
  both;

  String get label {
    switch (this) {
      case LearningMode.online:
        return 'Online';
      case LearningMode.offline:
        return 'Offline';
      case LearningMode.both:
        return 'Both';
    }
  }

  static LearningMode fromString(String value) {
    switch (value) {
      case 'online':
        return LearningMode.online;
      case 'offline':
        return LearningMode.offline;
      default:
        return LearningMode.both;
    }
  }
}

// ── 2. THE MODEL CLASS ───────────────────────
// A model is just a Dart class whose job is to
// hold data. It has NO UI and NO logic beyond
// converting itself to/from storage formats.

class SkillProfile {
  // ── 2a. FIELDS ────────────────────────────
  // These are the properties every profile has.
  // `final` means they can't be changed after
  // the object is created (immutable data is
  // safer and easier to reason about).

  /// A unique identifier so we can find / delete
  /// this exact profile later.
  /// Generated by the `uuid` package when saving.
  final String id;

  /// The student's display name.
  final String name;

  /// The skill this student can teach others.
  final String canTeachSkill;

  /// How good they are at what they can teach.
  final SkillLevel canTeachLevel;

  /// The skill this student wants to learn.
  final String wantToLearnSkill;

  /// What level they're aiming for / starting at.
  final SkillLevel wantToLearnLevel;

  /// Where they prefer to exchange skills.
  final LearningMode preferredMode;

  /// When this profile was created.
  /// Useful for sorting "newest first".
  final DateTime createdAt;

  // ── 2b. CONSTRUCTOR ───────────────────────
  // The constructor is called when you create
  // a new SkillProfile object, e.g.:
  //
  //   SkillProfile(
  //     id: '123',
  //     name: 'Aisha',
  //     canTeachSkill: 'Python',
  //     ...
  //   )
  //
  // Every field after `{` is a *named parameter*,
  // which makes call-sites readable.
  // `required` means the caller must provide it.

  const SkillProfile({
    required this.id,
    required this.name,
    required this.canTeachSkill,
    required this.canTeachLevel,
    required this.wantToLearnSkill,
    required this.wantToLearnLevel,
    required this.preferredMode,
    required this.createdAt,
  });

  // ── 2c. toJson() ──────────────────────────
  // Converts this object into a Map<String, dynamic>
  // which can be serialised to a JSON string
  // and saved to shared_preferences.
  //
  // Rule of thumb: every field becomes a key,
  // and its value becomes a storable type
  // (String, int, bool, double, List, Map).
  // Enums → store their .name (built-in string).
  // DateTime → store as milliseconds (an int).

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'canTeachSkill': canTeachSkill,
      // .name gives us the raw enum string, e.g. "beginner"
      'canTeachLevel': canTeachLevel.name,
      'wantToLearnSkill': wantToLearnSkill,
      'wantToLearnLevel': wantToLearnLevel.name,
      'preferredMode': preferredMode.name,
      // Store DateTime as milliseconds since epoch (an int)
      'createdAt': createdAt.millisecondsSinceEpoch,
    };
  }

  // ── 2d. fromJson() ────────────────────────
  // A *factory constructor* that does the reverse:
  // it takes a Map (loaded from storage) and
  // rebuilds a SkillProfile object from it.
  //
  // `factory` means this constructor can return
  // an existing object or do extra logic —
  // here we use it because we're converting types
  // rather than just assigning fields directly.

  factory SkillProfile.fromJson(Map<String, dynamic> json) {
    return SkillProfile(
      id: json['id'] as String,
      name: json['name'] as String,
      canTeachSkill: json['canTeachSkill'] as String,

      // Convert the stored string back to the enum
      canTeachLevel: SkillLevel.fromString(json['canTeachLevel'] as String),

      wantToLearnSkill: json['wantToLearnSkill'] as String,
      wantToLearnLevel:
          SkillLevel.fromString(json['wantToLearnLevel'] as String),

      preferredMode: LearningMode.fromString(json['preferredMode'] as String),

      // Convert milliseconds back to a DateTime object
      createdAt: DateTime.fromMillisecondsSinceEpoch(json['createdAt'] as int),
    );
  }

  // ── 2e. copyWith() ────────────────────────
  // Returns a NEW profile with some fields changed.
  // This is Flutter's standard way to "edit" an
  // immutable object without mutating the original.
  //
  // Usage example:
  //   final updated = profile.copyWith(name: 'New Name');

  SkillProfile copyWith({
    String? id,
    String? name,
    String? canTeachSkill,
    SkillLevel? canTeachLevel,
    String? wantToLearnSkill,
    SkillLevel? wantToLearnLevel,
    LearningMode? preferredMode,
    DateTime? createdAt,
  }) {
    return SkillProfile(
      // If a new value was passed in, use it.
      // Otherwise keep the current value (this.fieldName).
      id: id ?? this.id,
      name: name ?? this.name,
      canTeachSkill: canTeachSkill ?? this.canTeachSkill,
      canTeachLevel: canTeachLevel ?? this.canTeachLevel,
      wantToLearnSkill: wantToLearnSkill ?? this.wantToLearnSkill,
      wantToLearnLevel: wantToLearnLevel ?? this.wantToLearnLevel,
      preferredMode: preferredMode ?? this.preferredMode,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  // ── 2f. toString() ────────────────────────
  // Makes debugPrint(profile) show something
  // useful in the terminal instead of
  // "Instance of SkillProfile".

  @override
  String toString() {
    return 'SkillProfile('
        'id: $id, '
        'name: $name, '
        'teaches: $canTeachSkill (${canTeachLevel.label}), '
        'wants: $wantToLearnSkill (${wantToLearnLevel.label}), '
        'mode: ${preferredMode.label}'
        ')';
  }

  // ── 2g. MATCHING HELPER ───────────────────
  // Returns true if THIS profile matches another.
  // The rule: my desired skill == their offered skill.
  //
  // Used by the Matches screen to filter profiles.

  bool matchesWith(SkillProfile other) {
    // Don't match with yourself
    if (id == other.id) return false;

    // My wanted skill matches their teach skill
    final iWantWhatTheyTeach =
        wantToLearnSkill.toLowerCase().trim() ==
        other.canTeachSkill.toLowerCase().trim();

    // Learning mode compatibility
    final modeCompatible =
        preferredMode == LearningMode.both ||
        other.preferredMode == LearningMode.both ||
        preferredMode == other.preferredMode;
    final levelCompatible =
        other.canTeachLevel == wantToLearnLevel;

   return iWantWhatTheyTeach && modeCompatible && levelCompatible;
  }
}

