// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfXhPrlWs_FFXzUakY2Wbu9pFac88EoY',
    appId: '1:868363941569:web:6b21efbf0dc63c845f0640',
    messagingSenderId: '868363941569',
    projectId: 'skillswap-28e6b',
    authDomain: 'skillswap-28e6b.firebaseapp.com',
    storageBucket: 'skillswap-28e6b.firebasestorage.app',
    measurementId: 'G-C02QK5KN2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMzASMxm3Vx9ExcHPlW1zjI_shT9T4D1g',
    appId: '1:868363941569:android:ef581d4b0aa1b8f95f0640',
    messagingSenderId: '868363941569',
    projectId: 'skillswap-28e6b',
    storageBucket: 'skillswap-28e6b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfXhPrlWs_FFXzUakY2Wbu9pFac88EoY',
    appId: '1:868363941569:web:d1fdce2295258eb95f0640',
    messagingSenderId: '868363941569',
    projectId: 'skillswap-28e6b',
    authDomain: 'skillswap-28e6b.firebaseapp.com',
    storageBucket: 'skillswap-28e6b.firebasestorage.app',
    measurementId: 'G-M0YG1GLCF5',
  );
}
